[package]

name = "grpc"
version = "0.7.0"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Rust implementation of gRPC"
repository = "https://github.com/stepancheg/grpc-rust"
readme = "../README.md"
keywords = ["grpc"]

[dependencies]
log             = "0.4"
futures         = "0.1.*"
futures-cpupool = "0.1.*"
tokio-core      = "0.1.*"
tokio-io        = "0.1.*"
tokio-tls-api   = "0.1.*"
#httpbis         = "~0.7"
httpbis         = { git = "https://github.com/stepancheg/rust-http2", rev = "6b236c4" }
tls-api         = "0.1"
tls-api-stub    = "0.1"
bytes           = "0.4"
base64          = "0.9"

[dev-dependencies]
log-ndc-env-logger = "~0.2"

[lib]
doctest = false
